version: '3'

services:
  rustpad:
    build: .
    ports:
      - "3030:3030"
    volumes:
      - "./tmp/:/app/data/"
    environment:
      EXPIRY_DAYS: 14
      DATABASE_URI: 'sqlite://app/data/db.sqlite'
      PORT: 3030
      RUST_LOG:
      # DATABASE_URI: 'postgres://rustpad:rustpad@db:5432/rustpad'
    # depends_on:
    #   - db

  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_DB: rustpad
  #     POSTGRES_USER: rustpad
  #     POSTGRES_PASSWORD: rustpad
  #   ports:
  #     - "5432:5432"
